In [1]:
import numpy as np
from scipy import ndimage as ndi

In [2]:
r = np.random.randn(4096,4096)*3/2.

In [3]:
r.shape

(4096, 4096)

In [4]:

ndi

<module 'scipy.ndimage' from 'c:\\users\\npk\\virtualenv\\astropy\\lib\\site-packages\\scipy\\ndimage\\__init__.py'>

In [5]:
r

array([[ 2.27672057, -0.63430804,  2.60304051, ...,  0.10510857,
        -0.92900466, -1.66363195],
       [ 0.87390971, -1.30070399,  1.27062839, ..., -0.77382585,
        -0.22412883, -0.01850196],
       [ 1.43534405, -0.42337615,  1.32572211, ..., -0.19308557,
         0.50003951,  2.32610987],
       ...,
       [-0.46184517, -1.34466338, -1.59406497, ...,  2.97233418,
        -1.44049478, -0.37159086],
       [-0.55204907, -0.0247666 , -1.73381957, ..., -0.99785314,
        -0.12111198,  1.12243667],
       [-0.88651612, -0.84407196,  1.29742236, ..., -2.26330344,
         0.43822377, -1.32459044]])

In [6]:
d = 4096/11
np.arange(d,4096,d)

array([ 372.36363636,  744.72727273, 1117.09090909, 1489.45454545,
       1861.81818182, 2234.18181818, 2606.54545455, 2978.90909091,
       3351.27272727, 3723.63636364])

In [7]:
PSF = """  0.0000E+00	  0.0000E+00	  0.0000E+00	  0.0000E+00	  0.0000E+00	  0.0000E+00
  0.0000E+00	  0.0000E+00	  2.0672E+00	  2.7464E+01	  4.7250E+00	  0.0000E+00
  0.0000E+00	  0.0000E+00	  4.3529E+02	  6.3403E+02	  1.9491E+01	  0.0000E+00
  0.0000E+00	  0.0000E+00	  6.0332E+02	  6.8630E+02	  9.4500E+00	  0.0000E+00
  0.0000E+00	  0.0000E+00	  3.1598E+01	  3.2780E+01	  0.0000E+00	  0.0000E+00
  0.0000E+00	  0.0000E+00	  0.0000E+00	  2.9531E-01	  0.0000E+00	  0.0000E+00
"""

In [8]:
PSF

'  0.0000E+00\t  0.0000E+00\t  0.0000E+00\t  0.0000E+00\t  0.0000E+00\t  0.0000E+00\n  0.0000E+00\t  0.0000E+00\t  2.0672E+00\t  2.7464E+01\t  4.7250E+00\t  0.0000E+00\n  0.0000E+00\t  0.0000E+00\t  4.3529E+02\t  6.3403E+02\t  1.9491E+01\t  0.0000E+00\n  0.0000E+00\t  0.0000E+00\t  6.0332E+02\t  6.8630E+02\t  9.4500E+00\t  0.0000E+00\n  0.0000E+00\t  0.0000E+00\t  3.1598E+01\t  3.2780E+01\t  0.0000E+00\t  0.0000E+00\n  0.0000E+00\t  0.0000E+00\t  0.0000E+00\t  2.9531E-01\t  0.0000E+00\t  0.0000E+00\n'

In [9]:
psf=np.fromstring(PSF, sep="\t").reshape(6,6)

In [10]:
?np.fromstring

In [11]:
psf

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [0.0000e+00, 0.0000e+00, 2.0672e+00, 2.7464e+01, 4.7250e+00,
        0.0000e+00],
       [0.0000e+00, 0.0000e+00, 4.3529e+02, 6.3403e+02, 1.9491e+01,
        0.0000e+00],
       [0.0000e+00, 0.0000e+00, 6.0332e+02, 6.8630e+02, 9.4500e+00,
        0.0000e+00],
       [0.0000e+00, 0.0000e+00, 3.1598e+01, 3.2780e+01, 0.0000e+00,
        0.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 2.9531e-01, 0.0000e+00,
        0.0000e+00]])

In [12]:
imshow(psf)

NameError: name 'imshow' is not defined

In [ ]:
from pylab import *
imshow(psf)

In [ ]:
#PSF comes from zemax simulations
PSF = """  0.0000E+00	  0.0000E+00	  0.0000E+00	  0.0000E+00	  0.0000E+00	  0.0000E+00
  0.0000E+00	  0.0000E+00	  2.0672E+00	  2.7464E+01	  4.7250E+00	  0.0000E+00
  0.0000E+00	  0.0000E+00	  4.3529E+02	  6.3403E+02	  1.9491E+01	  0.0000E+00
  0.0000E+00	  0.0000E+00	  6.0332E+02	  6.8630E+02	  9.4500E+00	  0.0000E+00
  0.0000E+00	  0.0000E+00	  3.1598E+01	  3.2780E+01	  0.0000E+00	  0.0000E+00
  0.0000E+00	  0.0000E+00	  0.0000E+00	  2.9531E-01	  0.0000E+00	  0.0000E+00
"""

def really_fake_line_frame(n_fibers=10, n_pix=4096, counts=30000):
    """ Makes a really fake "emission line" spectrum """

    delta = n_pix/(n_fibers+1)
    img = np.zeros((n_pix,n_pix))

    w=3
    psf=np.fromstring(PSF, sep="\t").reshape(2*w,2*w)
    psf /= np.max(psf)
    
    psf *= counts

    dlines = n_pix/100
    poss = np.arange(delta, n_pix-delta, delta).astype(int)
    line_locs = np.arange(dlines,n_pix-dlines,delta).astype(int)
    for pos in poss:
        for line_loc in line_locs:
            s1 = slice(pos-w,pos+w)
            s2 = slice(line_loc-w,line_loc+w)
            img[s1,s2] = np.random.poisson(psf)
    
    return img

In [ ]:
fm = really_fake_line_frame()
fm2 = really_fake_line_frame()

d=fm-fm2

In [ ]:
imshow(d[360:380,390:420])

In [14]:
import timeit

In [20]:
sz = [1, 3, 10, 30]

sx = 0
sy = .5

for s in sz:
    a = np.random.randn(s,s)
    t = timeit.timeit(lambda:  ndi.shift(a, (sx, sy)))
    
    print("%i took %s" % (s,t))
    

1 took 29.2448767
3 took 20.8376808
10 took 29.9002282
30 took 92.9153829


In [15]:
from scipy.signal import convolve, convolve2d


In [41]:
#- Utility functions for sinc shifting pixelated PSFs
def _sincfunc(x, dx, dampfac=3.25):
    """sinc helper function for sincshift()"""
    if dx != 0.0:
        xx = (x+dx)*np.pi  #- cache shifted array for 30% faster evals
        return np.exp( -(xx/(dampfac*np.pi))**2 ) * np.sin(xx) / xx
    else:
        xx = np.zeros(len(x))
        xx[len(x)//2] = 1.0
        return xx
    
    
def sincshift2d(image, dx, dy, sincrad=10, dampfac=3.25):
    """
    Return image shifted by dx, dy using full 2D sinc interpolation
    """
    s = np.arange(-sincrad, sincrad+1.0)
    sincx = _sincfunc(s, -dx, dampfac=dampfac)
    sincy = _sincfunc(s, -dy, dampfac=dampfac)
    kernel = np.outer(sincy, sincx)
    newimage = convolve2d(image, kernel, mode='same')
    return newimage


In [42]:
a = np.random.randn(500,500)
%timeit sincshift2d(a, 0.5, 0.5);

240 ms ± 237 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [47]:
a = np.zeros((5,5))
a[2,2] = 1
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
sincshift2d(a,-1.5,0)

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.62172877,  0.62172877, -0.17149301,  0.07045813, -0.02851696],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [ ]:
a

In [ ]:

s=(slice(100,200),slice(100,200))
a[s]

In [ ]:
def x(t):
    print (t)



list(map(x, [(i,j) for i in range(3) for j in range(3)]))

In [ ]:
data = {"T": 3}
for k,v in data.items():
    exec("%s=data['%s']" % (k,k))

In [ ]:
subsample = 20
pm_pixels = 1

stepsize = pm_pixels*2/(subsample+1)
for ix in range(subsample):
    for jx in range(subsample):
        sx = -pm_pixels + stepsize*ix
        sy = -pm_pixels + stepsize*jx
        
        print(sx,sy)

In [50]:
around = np.array([[0,0,1],[0,0,0]])

In [53]:
np.argmax(around, axis=1)

array([2, 0], dtype=int64)